#%RAML 1.0 DataType  
type: object
properties:
  name:
    type: string
    required: true
  surname:
    type: string
    required: true    
  mail: 
    type: string
    required: true
  address:
    type: string
    required: true