#%RAML 1.0 NamedExample
  value:
  -
    id: 1
    name: simone
    surname: proietti
    mail: "simone.proietti@x3solutions.it"
    address: "Via Montanara, 7 Terni"
  -
    id: 2
    name: simone
    surname: proietti
    mail: "simone.proietti2@x3solutions.it"
    address: "Via Montanara, 7 Terni (TR)"